server:
  port: 80
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/xxl_job?Unicode=true&characterEncoding=UTF-8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: xxl-job-demo
      ip:
      port: 9999
      logpath: "/data/applogs/xxl-job/jobhandler"
      logretentiondays: -1
    accessToken:
  version: 1.0.0

logging:
  config: classpath:logback.xml